Always set triton allocator
On the latest triton, some tests failed with:
RuntimeError: Kernel requires a runtime memory allocation, but no allocator was set. Use triton.set_allocator to specify an allocator.

stack-info: PR: https://github.com/pytorch-labs/helion/pull/416, branch: jansel/stack/126