Handle torch.version missing xpu attribute (#1363)
Summary:

Addresses the following error, which was found while enabling a Helion layernorm kernel on MTIA.

```
  File "/data/sandcastle/boxes/fbsource/buck-out/v2/gen/fbcode/e99d3107bebd6931/ads_mkl/ops/helion/tests/__helion_layernorm_test_mtia_athena_qmodel-inner__/helion_layernorm_test_mtia_athena_qmodel-inner#link-tree/helion/_compat.py", line 333, in _supports_maxnreg
    return torch.version.hip is None and torch.version.xpu is None
                                         ^^^^^^^^^^^^^^^^^
AttributeError: module 'torch.version' has no attribute 'xpu'
```
More details at T253250124

Reviewed By: nhat-nguyen

Differential Revision: D91800408