Do not create a new variable for tile assignments since tiles are immutable
Fixes #332

Previously it was erroring with
```
helion.exc.InternalError: RuntimeError: Tile(0) (139684109802224)is not
tracked with proxy for
<torch.fx.experimental.proxy_tensor.PythonKeyTracer object at
0x7f0abf06cc90>
```

stack-info: PR: https://github.com/pytorch-labs/helion/pull/334, branch: oulgen/stack/24