Enable gradient tracking for 'y' in mul_relu_block_back_spec
I was getting an error. Resolved after enabling gradient checking for y

```
RuntimeError: One of the differentiated Tensors does not require grad
```